stages:
  train:
    cmd: python src/train.py
    deps:
    - SF_dataset
    - src
    params:
    - params.yaml:
    outs:
    - weights
    metrics:
    - metrics.json:
        cache: false
    plots:
    - plots:
        cache: false
