stages:
  train:
    cmd: python src/train.py
    deps:
    - SF_dataset
    - src
    params:
    - params.yaml:
    outs:
    - weights
    metrics:
    - dvclive.json:
        cache: false
    plots:
    - dvclive/train_accuracy.jpg
    - dvclive/train_loss.jpg
